#어플리케이션 포트 -> 디폴트가 8080
server:
  port: 8080

imp:
  v1:
    api:
      key: 4320034802014282
      secret: LqAANgPmihhWeqIsGqAf9AwbauTSUvBXGYRzGqI8ZbVRBciDNnoeWelBRYfmiPhAnCunTRSop2ZuBC4a

coolsms:
  api:
    key: NCSLHTOI7EIIPLOE
    secret: FVN9TI49XHWDDXEVAG0SLZNUYI2IZIZP
    number: 01056766769

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/what_tv?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: whatTv
    password: 135798

  servlet:
    multipart:
      max-file-size: 10000MB   # 업로드 가능한 파일의 최대 크기
      max-request-size: 10000MB # 업로드 가능한 요청 전체의 최대 크기

file:
  boardImagePath: /Users/jun/SpringBoot/what_tv/src/main/resources/static/images/
  profileImagePath: /Users/jun/SpringBoot/what_tv/src/main/resources/static/profileImage/



jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  open-in-view: false
  show-sql: true
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
    ddl-auto: update
    highlight_sql : true
  defer-datasource-initailization: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



# mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml